% Load known connected files
load( 'TestData\testConnFiles.mat' )

%% Test connected status
connTst = [ true true true true false ]';
assert( isequal( conn, connTst ) )

%% Test file names
fnTst =  {...
    'sampleCSC2-17.ncs';...
    'sampleCSC2-28.ncs';...
    'sampleCSC3-23.ncs';...
    'sampleCSC3-25.ncs';...
    'sampleEmptyCSC3-7.ncs' };
assert( isequal( fn, fnTst ) )